spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 16385
    host: 127.0.0.1
    password: 1747
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test
    password:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #username: root
    #url: jdbc:mysql://localhost:3306/finaldemo?serverTimezone=Asia/Seoul
    #password: 1234
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-Auto: create-drop
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  mvc:
    converters:
      preferred-json-mapper: jackson
    static-path-pattern: /resources/**
  thymeleaf:
    prefix: classpath:/static/
  data:
    web:
      pageable:
        one-indexed-parameters: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 541309009451-92mhcite978a3ortbm2c6ruce68hr0lj.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://otakubot.store:20101/login/oauth2/code/google
            scope:
              - profile
              - email
          kakao:
            client-id: 6a4bb2fa60ad461ae820953255846ebf
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: https://otakubot.store:20101:20101/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  web:
    resources:
      static-locations: "classpath:/resources/"

logging:
  level:
    root: info
  file:
    name: log/app.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
      max-file-size: 1MB
app:
  fileupload:
    uploadPath: /SSAFY/dummy/fisher
    uploadDir: upload
jwt:
  secret-key: ihatejavascriptihatevuefuckyoujavascriptfuckyouvuefreehongkong
  access-token-expiration-sec: 1800
  refresh-token-expiration-sec: 1209600

mail:
  address:
    admin: ssafy@ssafy.com
server:
  port: 7070
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-type: PKCS12
    key-store-password: cjswo1!

