version: '3.8'

services:
  spring:
    build:
      context: ./back/Spring/fisher
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-redis
    depends_on:
      - redis
    container_name: spring

  redis:
    image: "redis:latest"
    command: ["redis-server", "--requirepass", "1747"]
    ports:
      - "6379:6379"
    networks:
      - spring-redis
    container_name: redis

  nginx:
    build:
      context: ./front
      dockerfile: dockerfile
    ports:
      - "443:443"
      - "80:80"
    networks:
      - spring-redis
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    container_name: nginx

networks:
  spring-redis:
    driver: bridge

volumes:
  vol: