version: '3'

services:
  spring:
    build:
      context: ./back/Spring/fisher
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-redis
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    command: ["redis-server", "--requirepass", "1747"]
    ports:
      - "6379:6379"
    networks:
      - spring-redis

  react:
    build:
      context: ./front
      dockerfile: dockerfile
    ports:
      - "443:443"
      - "80:80"
    networks:
      - spring-redis
    volumes:
      - vol:/etc/letsencrypt

networks:
  spring-redis:
    driver: bridge

volumes:
  vol: {}