version: '3'

services:
  spring:
    build:
      context: ./back/Spring/fisher
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    command: ["redis-server", "--requirepass", "1747"]
    ports:
      - "6379:6379"

  react:
    build:
      context: ./front
      dockerfile: dockerfile
    ports:
      - "3000:3000"
